// Brand list with the other spellings people type, and patterns that recognise the brand in a product name.
// [Thai name, English name, extra search words, name patterns (tested on the lower-case name without spaces)]
// Existing brands keep their position in the stored list; new ones are appended, so product links never shift.
export const BRAND_RULES_VERSION = 4;
export const BRAND_RULES = [
  ['สมาร์ทฮาร์ท', 'SmartHeart', ['sm', 'sh', 'smh', 'shg', 's/h', 'smart heart', 'สมาร์ท'], [/^sm(?![a-z])/, /^smtoy/, /^sh(?![a-z])/, /^shg/, /^s\/h/, /^smh/, /สมาร์ทฮาร์ท/, /สมาร์ฮาร์ท/, /smartheart/]],
  ['มีโอ', 'Me-O', ['meo', 'me o', 'มีโอ้'], [/me-?o/, /มีโอ/]],
  ['เพดดีกรี', 'Pedigree', ['pd', 'เพดดิกรี'], [/pedigree/, /เพดดีกรี/, /เพดดิกรี/]],
  ['วิสกัส', 'Whiskas', [], [/whiskas/, /วิสกัส/]],
  ['รอยัลคานิน', 'Royal Canin', ['ry', 'r/y', 'royalcanin', 'โรยัล'], [/royal/, /รอยัล/, /โรยัล/, /^r\/y/, /^ry(?![a-z])/]],
  ['เจอร์ไฮ', 'Jerhigh', ['j/h', 'jh', 'เจอไฮ', 'เจอร์ไฮน์'], [/jerhi(g|gn)h?/, /เจอไฮ/, /เจอร์ไฮ/, /^j\/h/]],
  ['คานิว่า', 'Kaniva', [], [/kaniva/, /คานิว่า/]],
  ['พรามี่', 'Pramy', [], [/pramy/, /พรามี่/]],
  ['เพียวริน่า', 'Purina', ['purinaone', 'proplan', 'เพียวริน่าวัน'], [/purina/, /เพียวริน่า/]],
  ['ฟริสกี้ส์', 'Friskies', ['ฟริสกี้'], [/friskies/, /ฟริสกี้/]],
  ['ออสเทค', 'Ostech', [], [/ostech/, /ออสเทค/]],
  ['เบลลอตต้า', 'Bellotta', ['belotta', 'เบลอตตา', 'เบลล็อตต้า'], [/bel+otta/, /เบลลอตต้า/, /เบลอตตา/, /เบล็อตต้า/]],
  ['แคทตี้แคท', 'Catty Cat', ['cattycat'], [/cattycat/, /แคทตี้แคท/]],
  ['บัซ', 'Buzz', [], [/buzz/]],
  ['เพ็ทเอท', 'Pet8', ['pet 8', 'pet-8'], [/^pet-?8/, /เพ็ทเอท/]],
  ['มองชู', 'Monchou', [], [/monchou/, /มองชู/]],
  ['เน็กโกะ', 'Nekko', [], [/nekko/, /เน็กโกะ/]],
  ['ไฮไลฟ์', 'Hi Life', ['hilife'], [/hilife/, /ไฮไลฟ์/]],
  ['ออพติมั่ม', 'Optimum', ['ออฟติมั่ม'], [/optimum/, /ออ[พฟ]ติมั่ม/]],
  ['สลิคกี้', 'Sleeky', [], [/sleeky/, /สลิคกี้/]],
  ['บ็อกด็อก', 'Bok Dok', ['bokdok', 'b/d', 'บ๊อกด๊อก'], [/bokdok/, /^b\/d/, /บ[็๊]อกด[็๊]อก/]],
  ['วีไอเอฟ', 'VIF', [], [/^vif/]],
  ['โทโร่', 'Toro', [], [/toro/, /โทโร่/]],
  ['เชาว์', 'Ciao', ['เชา'], [/ciao/, /เชาว์/]],
  ['ไลฟ์เมท', 'Lifemate', ['lifrmate'], [/lifemate/, /lifrmate/]],
  ['เพ็ทเฮง', 'Petheng', ['pet heng'], [/petheng/, /เพ็ทเฮง/]],
  ['โอกิโกะ', 'Okiko', [], [/okiko/]],
  ['มูชี่', 'Moochie', [], [/moochie/, /มูชี่/]],
  ['แดดดี้ด็อก', 'Daddy Dog', ['daddydog'], [/daddy/]],
  ['แคสตี้', 'Kasty', [], [/kasty/]],
  ['แบร์ริ่ง', 'Bearing', ['แบรริ่ง'], [/bearing/, /แบร์ริ่ง/, /แบรริ่ง/]],
  ['เชนการ์ด', 'Chaingard', [], [/เชนการ์ด/, /chaingard/]],
  ['คานิมอล', 'Kanimal', [], [/kanimal/]],
  ['โมจิ', 'Mochi', [], [/mochi/]],
  ['มันซ์นี่', 'Munznie', [], [/munznie/]],
  ['ด็อกเอ็นจอย', 'Dog n Joy', ['dnj', 'dognjoy'], [/ด็อกเอ็นจอย/, /dognjoy/, /^dnj/]],
  ['แคทเอ็นจอย', 'Cat n Joy', ['cnj', 'catnjoy'], [/catnjoy/, /แคทเอ็นจอย/, /^cnj/]],
  ['แม็คเคลลี่', 'McKelly', ['แมคแคลลี่', 'แมคเคลลี่'], [/mckelly/, /แม[็]?คแคลลี/, /แม[็]?คเคลลี/]],
  ['เลิฟแคร์', 'Luvcare', ['luv care'], [/luvcare/, /^luv/]],
  ['ฮาจิโกะ', 'Hajiko', [], [/hajiko/, /ฮาจิโกะ/]],
  ['รีกาลอส', 'Regalos', [], [/regalos/, /รีกาลอส/]],
  ['เพอร์เฟคต้า', 'Perfecta', [], [/perfecta/]],
  ['เทมเทชันส์', 'Temptations', ['เทมเทชัน'], [/temptation/, /เทมเทชัน/]],
  ['เดนต้าสติก', 'Dentastix', ['เดนต้า'], [/dentastix/, /เด[็]?นต้าส/]],
  ['แม็กซิม่า', 'Maxima', [], [/maxima/, /แม็กซิม่า/]],
  ['แคนดี้', 'Kandy', [], [/^kandy/, /แคนดี้/]],
  ['ซอยแคท', 'Zoi Cat', ['zoicat'], [/zoicat/, /ซอยแคท/]],
  ['จินโน่', 'Ginno', [], [/ginno/]],
  ['นีซ', 'Neez', [], [/neez/]],
  ['พอดี้', 'Pawdy', [], [/pawdy/]],
  ['บูมบูม', 'Boomboom', [], [/boomboom/]],
  ['บิงโกสตาร์', 'Bingo Star', ['bingostar'], [/bingo/, /บิงโก/]],
  ['วินสตาร์', 'Winstar', [], [/วินสตาร์/, /winstar/]],
  ['ชีบา', 'Sheba', [], [/sheba/, /ชีบา/]],
  ['คิทแคท', 'Kitcat', [], [/^kitcat/, /คิทแคท/]],
  ['ซิลเวอร์', 'Silver', [], [/ซิลเวอร์/, /^silver/]],
  ['วีเอฟคอร์', 'VF Core', ['vfcore'], [/vf ?core/]],
  ['เหมียวเหมียว', 'Meow Meow', [], [/เหมียวเหมียว/]],
  ['โอลิเวอร์', 'Oliver', [], [/^oliver/, /โอลิเวอร์/]],
  ['จินนี่', 'Jinny', [], [/jinny/, /จินนี่/]],
  ['คิสมี', 'Kiss Me', ['kissme'], [/kiss ?me/, /คิสมี/]],
  ['มาร์โว่', 'Marvo', [], [/marvo/, /มาร์โว่/]],
  ['เฮอร์คิวลิส', 'Hercules', [], [/hercules/]],
  // added in version 2
  ['โปรแคท', 'ProCat', ['pro cat'], [/procat/, /โปรแคท/]],
  ['เอโปร', 'A Pro', ['apro', 'a pro iq', 'เอโปรไอคิว'], [/^a-?pro/, /เอโปร/]],
  ['เลิฟมี', 'Love Me', ['loveme'], [/loveme/, /เลิฟมี/]],
  ['มิสเตอร์เว็ท', 'Mr.Vet', ['mrvet', 'mr vet'], [/mr\.?vet/]],
  ['บราโวบอส', 'Bravo Boss', ['bravoboss'], [/บราโวบอส/, /bravoboss/]],
  ['โอเล่แคท', 'Ole Cat', ['olecat'], [/โอเล่แคท/, /olecat/]],
  ['แคตตี้พาวส์', 'Cattie Paws', ['cattiepaws'], [/cattiepaws/, /แคตตี้พาว/]],
  ['ซินดี้', 'Cindy Recipe', ['cindy', 'cindyrecipe'], [/cindy/, /ซินดี้/]],
  ['แคทซิตต้า', 'Catzitta', [], [/catzitta/, /แคทซิตต้า/]],
  ['เฟลิกซ์', 'Felix', [], [/felix/, /เฟลิกซ์/]],
  ['ซีซ่า', 'Cesar', [], [/cesar/, /ซีซ่า/]],
  ['โฮ่งโฮ่ง', 'Hong Hong', [], [/โฮ่งโฮ่ง/]],
  ['แคทตี้โปร', 'Catty Pro', ['cattypro', 'แคตตี้โปร'], [/cattypro/, /แค[ทต]ตี้โปร/]],
  ['ฟรอนท์ไลน์', 'Frontline', [], [/frontline/, /ฟรอนท์ไลน์/]],
  ['ฟรอนท์การ์ด', 'FrontGuard', [], [/frontguard/, /ฟรอนท์กา/]],
  ['เน็กซ์การ์ด', 'NexGard', ['nexgard'], [/nexgard/, /เน็กซ์การ์ด/]],
  ['บราเวคโต', 'Bravecto', [], [/bravecto/, /บราเว[็]?คโต/]],
  ['เพ็ทเทอเรีย', 'Petheria', [], [/petheria/]],
  ['โลล่า', 'Lola & Co', ['lola'], [/^lola/, /โลล่า/]],
  ['โทชิแคท', 'Toshi Cat', ['toshicat'], [/toshicat/, /โทชิ/]],
  ['แคทโตะ', 'Katto', [], [/^katto/, /แคทโตะ/]],
  ['พอลลี่', 'Paully', [], [/paully/, /พอลลี่/]],
  ['ดีนี่แคท', 'Deenee Cat', ['deeneecat'], [/deeneecat/, /ดีนี่/]],
  ['ซอยด็อก', 'Zoi Dog', ['zoidog'], [/zoidog/, /ซอยด็อก/]],
  ['เคนตะ', 'Kenta', [], [/kenta/, /เคนตะ/]],
  ['เพ็ทไพรม์', 'Pet Prime', ['petprime'], [/petprime/, /เพ็ทไพรม์/]],
  ['เพ็ทโพรเทค', 'Pet Protect', ['petprotect'], [/petprotect/, /เพ็ทโพรเทค/]],
  ['เวทริแม็กซ์', 'VetriMax', ['vetrimax'], [/vetrimax/, /เวทริ/]],
  ['โอคาชิ', 'Okashi', [], [/okashi/, /โอคาชิ/]],
  ['มาวว้าว', 'MowWow', ['mowwow'], [/mowwow/]],
  ['ชินจิ', 'Chin-Ji', ['chinji'], [/chin-?ji/, /ชินจิ/]],
  ['เอ็กซ์ตร้า', 'Extra Treats', ['extratreats'], [/extratreats/]],
  // added in version 3
  ['เชอร์แมน', 'Cherman', ['cherman', 'เชอแมน', 'เชอร์แมนท์'], [/cherman/, /เชอร์?แมน/]],
  // added in version 4
  ['อีซี่แคท', 'Easy Cat', ['easycat', 'easy cat', 'อีซี่', 'อีซีแคท'], [/easy-?cat/, /อีซี่?แคท/]],
  ['พาวเวอร์แคท', 'PowerCat', ['powercat', 'power cat'], [/power-?cat/, /พาวเวอร์แคท/]],
  ['โปริ', 'Pori', ['pori', 'โพริ'], [/pori/, /โปริ/, /โพริ/]],
];
const norm = s => String(s ?? '').toLowerCase().replace(/\s+/g, '');
export function detectBrand(name) {
  const n = norm(name);
  for (let i = 0; i < BRAND_RULES.length; i++) if (BRAND_RULES[i][3].some(re => re.test(n))) return i;
  return -1;
}
